version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: broton
      POSTGRES_PASSWORD: secret
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ell.patron91@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
  pgadmin_data: